# golangci-lint configuration for provider-upjet-tailscale
run:
  timeout: 10m
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - misspell
    - revive
    - unconvert
    - gocyclo
    - goconst
    - unparam

  disable:
    - structcheck  # deprecated
    - deadcode     # deprecated
    - varcheck     # deprecated

linters-settings:
  goimports:
    local-prefixes: github.com/millstonehq/mill/providers/provider-upjet-tailscale

  revive:
    rules:
      - name: exported
        disabled: false
        arguments:
          - "checkPrivateReceivers"
          - "sayRepetitiveInsteadOfStutters"

  gocyclo:
    min-complexity: 15

  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - goconst

    # Exclude generated files
    - path: zz_.*\.go
      linters:
        - goimports
        - gofmt
        - govet
        - errcheck
        - staticcheck

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
