// Package controller contains the controller setup.
package controller

import (
	"sigs.k8s.io/controller-runtime/pkg/manager"

	"github.com/crossplane/crossplane-runtime/pkg/controller"
	"github.com/crossplane/upjet/pkg/controller"

	"github.com/millstonehq/provider-upjet-tailscale/internal/clients"
)

// Setup sets up all controllers.
func Setup(mgr manager.Manager, o controller.Options) error {
	// Note: The actual controller registrations will be generated by upjet
	// This is a placeholder that will be populated after code generation

	// The upjet code generator will add controller.Setup calls here for each resource
	// Example (will be generated):
	// if err := acl.Setup(mgr, o); err != nil {
	//     return err
	// }

	return nil
}
