/*
Copyright 2025 Millstone HQ.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type IntegrationInitParameters struct {

	// Unique identifier for your client.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// The secret (auth key, token, etc.) used to authenticate with the provider.
	ClientSecret *string `json:"clientSecret,omitempty" tf:"client_secret,omitempty"`

	// Identifies which of the provider's clouds to integrate with.
	CloudID *string `json:"cloudId,omitempty" tf:"cloud_id,omitempty"`

	// The type of posture integration data provider.
	PostureProvider *string `json:"postureProvider,omitempty" tf:"posture_provider,omitempty"`

	// The Microsoft Intune directory (tenant) ID. For other providers, this is left blank.
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type IntegrationObservation struct {

	// Unique identifier for your client.
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// The secret (auth key, token, etc.) used to authenticate with the provider.
	ClientSecret *string `json:"clientSecret,omitempty" tf:"client_secret,omitempty"`

	// Identifies which of the provider's clouds to integrate with.
	CloudID *string `json:"cloudId,omitempty" tf:"cloud_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The type of posture integration data provider.
	PostureProvider *string `json:"postureProvider,omitempty" tf:"posture_provider,omitempty"`

	// The Microsoft Intune directory (tenant) ID. For other providers, this is left blank.
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

type IntegrationParameters struct {

	// Unique identifier for your client.
	// +kubebuilder:validation:Optional
	ClientID *string `json:"clientId,omitempty" tf:"client_id,omitempty"`

	// The secret (auth key, token, etc.) used to authenticate with the provider.
	// +kubebuilder:validation:Optional
	ClientSecret *string `json:"clientSecret,omitempty" tf:"client_secret,omitempty"`

	// Identifies which of the provider's clouds to integrate with.
	// +kubebuilder:validation:Optional
	CloudID *string `json:"cloudId,omitempty" tf:"cloud_id,omitempty"`

	// The type of posture integration data provider.
	// +kubebuilder:validation:Optional
	PostureProvider *string `json:"postureProvider,omitempty" tf:"posture_provider,omitempty"`

	// The Microsoft Intune directory (tenant) ID. For other providers, this is left blank.
	// +kubebuilder:validation:Optional
	TenantID *string `json:"tenantId,omitempty" tf:"tenant_id,omitempty"`
}

// IntegrationSpec defines the desired state of Integration
type IntegrationSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     IntegrationParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider IntegrationInitParameters `json:"initProvider,omitempty"`
}

// IntegrationStatus defines the observed state of Integration.
type IntegrationStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        IntegrationObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Integration is the Schema for the Integrations API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,tailscale}
type Integration struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.clientSecret) || (has(self.initProvider) && has(self.initProvider.clientSecret))",message="spec.forProvider.clientSecret is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.postureProvider) || (has(self.initProvider) && has(self.initProvider.postureProvider))",message="spec.forProvider.postureProvider is a required parameter"
	Spec   IntegrationSpec   `json:"spec"`
	Status IntegrationStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// IntegrationList contains a list of Integrations
type IntegrationList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Integration `json:"items"`
}

// Repository type metadata.
var (
	Integration_Kind             = "Integration"
	Integration_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Integration_Kind}.String()
	Integration_KindAPIVersion   = Integration_Kind + "." + CRDGroupVersion.String()
	Integration_GroupVersionKind = CRDGroupVersion.WithKind(Integration_Kind)
)

func init() {
	SchemeBuilder.Register(&Integration{}, &IntegrationList{})
}
