/*
Copyright 2025 Millstone HQ.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ACLInitParameters struct {

	// The policy that defines which devices and users are allowed to connect in your network. Can be either a JSON or a HuJSON string.
	ACL *string `json:"acl,omitempty" tf:"acl,omitempty"`

	// If true, will skip requirement to import acl before allowing changes. Be careful, can cause ACL to be overwritten
	OverwriteExistingContent *bool `json:"overwriteExistingContent,omitempty" tf:"overwrite_existing_content,omitempty"`

	// If true, will reset the ACL for the Tailnet to the default when this resource is destroyed
	ResetACLOnDestroy *bool `json:"resetAclOnDestroy,omitempty" tf:"reset_acl_on_destroy,omitempty"`
}

type ACLObservation struct {

	// The policy that defines which devices and users are allowed to connect in your network. Can be either a JSON or a HuJSON string.
	ACL *string `json:"acl,omitempty" tf:"acl,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// If true, will skip requirement to import acl before allowing changes. Be careful, can cause ACL to be overwritten
	OverwriteExistingContent *bool `json:"overwriteExistingContent,omitempty" tf:"overwrite_existing_content,omitempty"`

	// If true, will reset the ACL for the Tailnet to the default when this resource is destroyed
	ResetACLOnDestroy *bool `json:"resetAclOnDestroy,omitempty" tf:"reset_acl_on_destroy,omitempty"`
}

type ACLParameters struct {

	// The policy that defines which devices and users are allowed to connect in your network. Can be either a JSON or a HuJSON string.
	// +kubebuilder:validation:Optional
	ACL *string `json:"acl,omitempty" tf:"acl,omitempty"`

	// If true, will skip requirement to import acl before allowing changes. Be careful, can cause ACL to be overwritten
	// +kubebuilder:validation:Optional
	OverwriteExistingContent *bool `json:"overwriteExistingContent,omitempty" tf:"overwrite_existing_content,omitempty"`

	// If true, will reset the ACL for the Tailnet to the default when this resource is destroyed
	// +kubebuilder:validation:Optional
	ResetACLOnDestroy *bool `json:"resetAclOnDestroy,omitempty" tf:"reset_acl_on_destroy,omitempty"`
}

// ACLSpec defines the desired state of ACL
type ACLSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ACLParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ACLInitParameters `json:"initProvider,omitempty"`
}

// ACLStatus defines the observed state of ACL.
type ACLStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ACLObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ACL is the Schema for the ACLs API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,tailscale}
type ACL struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.acl) || (has(self.initProvider) && has(self.initProvider.acl))",message="spec.forProvider.acl is a required parameter"
	Spec   ACLSpec   `json:"spec"`
	Status ACLStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ACLList contains a list of ACLs
type ACLList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ACL `json:"items"`
}

// Repository type metadata.
var (
	ACL_Kind             = "ACL"
	ACL_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ACL_Kind}.String()
	ACL_KindAPIVersion   = ACL_Kind + "." + CRDGroupVersion.String()
	ACL_GroupVersionKind = CRDGroupVersion.WithKind(ACL_Kind)
)

func init() {
	SchemeBuilder.Register(&ACL{}, &ACLList{})
}
