/*
Copyright 2025 Millstone HQ.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type PreferencesInitParameters struct {

	// Whether or not to enable magic DNS
	MagicDNS *bool `json:"magicDns,omitempty" tf:"magic_dns,omitempty"`
}

type PreferencesObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether or not to enable magic DNS
	MagicDNS *bool `json:"magicDns,omitempty" tf:"magic_dns,omitempty"`
}

type PreferencesParameters struct {

	// Whether or not to enable magic DNS
	// +kubebuilder:validation:Optional
	MagicDNS *bool `json:"magicDns,omitempty" tf:"magic_dns,omitempty"`
}

// PreferencesSpec defines the desired state of Preferences
type PreferencesSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PreferencesParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PreferencesInitParameters `json:"initProvider,omitempty"`
}

// PreferencesStatus defines the observed state of Preferences.
type PreferencesStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PreferencesObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Preferences is the Schema for the Preferencess API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,tailscale}
type Preferences struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.magicDns) || (has(self.initProvider) && has(self.initProvider.magicDns))",message="spec.forProvider.magicDns is a required parameter"
	Spec   PreferencesSpec   `json:"spec"`
	Status PreferencesStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PreferencesList contains a list of Preferencess
type PreferencesList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Preferences `json:"items"`
}

// Repository type metadata.
var (
	Preferences_Kind             = "Preferences"
	Preferences_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Preferences_Kind}.String()
	Preferences_KindAPIVersion   = Preferences_Kind + "." + CRDGroupVersion.String()
	Preferences_GroupVersionKind = CRDGroupVersion.WithKind(Preferences_Kind)
)

func init() {
	SchemeBuilder.Register(&Preferences{}, &PreferencesList{})
}
