/*
Copyright 2025 Millstone HQ.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type SearchPathsInitParameters struct {

	// Devices on your network will use these domain suffixes to resolve DNS names.
	SearchPaths []*string `json:"searchPaths,omitempty" tf:"search_paths,omitempty"`
}

type SearchPathsObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Devices on your network will use these domain suffixes to resolve DNS names.
	SearchPaths []*string `json:"searchPaths,omitempty" tf:"search_paths,omitempty"`
}

type SearchPathsParameters struct {

	// Devices on your network will use these domain suffixes to resolve DNS names.
	// +kubebuilder:validation:Optional
	SearchPaths []*string `json:"searchPaths,omitempty" tf:"search_paths,omitempty"`
}

// SearchPathsSpec defines the desired state of SearchPaths
type SearchPathsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SearchPathsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SearchPathsInitParameters `json:"initProvider,omitempty"`
}

// SearchPathsStatus defines the observed state of SearchPaths.
type SearchPathsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SearchPathsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SearchPaths is the Schema for the SearchPathss API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,tailscale}
type SearchPaths struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.searchPaths) || (has(self.initProvider) && has(self.initProvider.searchPaths))",message="spec.forProvider.searchPaths is a required parameter"
	Spec   SearchPathsSpec   `json:"spec"`
	Status SearchPathsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SearchPathsList contains a list of SearchPathss
type SearchPathsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SearchPaths `json:"items"`
}

// Repository type metadata.
var (
	SearchPaths_Kind             = "SearchPaths"
	SearchPaths_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SearchPaths_Kind}.String()
	SearchPaths_KindAPIVersion   = SearchPaths_Kind + "." + CRDGroupVersion.String()
	SearchPaths_GroupVersionKind = CRDGroupVersion.WithKind(SearchPaths_Kind)
)

func init() {
	SchemeBuilder.Register(&SearchPaths{}, &SearchPathsList{})
}
