/*
Copyright 2025 Millstone HQ.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AccountInitParameters struct {

	// Email address to send communications to
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type AccountObservation struct {

	// Email address to send communications to
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type AccountParameters struct {

	// Email address to send communications to
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`
}

type ContactsInitParameters struct {

	// Configuration for communications about important changes to your tailnet
	Account []AccountInitParameters `json:"account,omitempty" tf:"account,omitempty"`

	// Configuration for communications about security issues affecting your tailnet
	Security []SecurityInitParameters `json:"security,omitempty" tf:"security,omitempty"`

	// Configuration for communications about misconfigurations in your tailnet
	Support []SupportInitParameters `json:"support,omitempty" tf:"support,omitempty"`
}

type ContactsObservation struct {

	// Configuration for communications about important changes to your tailnet
	Account []AccountObservation `json:"account,omitempty" tf:"account,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Configuration for communications about security issues affecting your tailnet
	Security []SecurityObservation `json:"security,omitempty" tf:"security,omitempty"`

	// Configuration for communications about misconfigurations in your tailnet
	Support []SupportObservation `json:"support,omitempty" tf:"support,omitempty"`
}

type ContactsParameters struct {

	// Configuration for communications about important changes to your tailnet
	// +kubebuilder:validation:Optional
	Account []AccountParameters `json:"account,omitempty" tf:"account,omitempty"`

	// Configuration for communications about security issues affecting your tailnet
	// +kubebuilder:validation:Optional
	Security []SecurityParameters `json:"security,omitempty" tf:"security,omitempty"`

	// Configuration for communications about misconfigurations in your tailnet
	// +kubebuilder:validation:Optional
	Support []SupportParameters `json:"support,omitempty" tf:"support,omitempty"`
}

type SecurityInitParameters struct {

	// Email address to send communications to
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type SecurityObservation struct {

	// Email address to send communications to
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type SecurityParameters struct {

	// Email address to send communications to
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`
}

type SupportInitParameters struct {

	// Email address to send communications to
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type SupportObservation struct {

	// Email address to send communications to
	Email *string `json:"email,omitempty" tf:"email,omitempty"`
}

type SupportParameters struct {

	// Email address to send communications to
	// +kubebuilder:validation:Optional
	Email *string `json:"email" tf:"email,omitempty"`
}

// ContactsSpec defines the desired state of Contacts
type ContactsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ContactsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ContactsInitParameters `json:"initProvider,omitempty"`
}

// ContactsStatus defines the observed state of Contacts.
type ContactsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ContactsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Contacts is the Schema for the Contactss API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,tailscale}
type Contacts struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.account) || (has(self.initProvider) && has(self.initProvider.account))",message="spec.forProvider.account is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.security) || (has(self.initProvider) && has(self.initProvider.security))",message="spec.forProvider.security is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.support) || (has(self.initProvider) && has(self.initProvider.support))",message="spec.forProvider.support is a required parameter"
	Spec   ContactsSpec   `json:"spec"`
	Status ContactsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ContactsList contains a list of Contactss
type ContactsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Contacts `json:"items"`
}

// Repository type metadata.
var (
	Contacts_Kind             = "Contacts"
	Contacts_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Contacts_Kind}.String()
	Contacts_KindAPIVersion   = Contacts_Kind + "." + CRDGroupVersion.String()
	Contacts_GroupVersionKind = CRDGroupVersion.WithKind(Contacts_Kind)
)

func init() {
	SchemeBuilder.Register(&Contacts{}, &ContactsList{})
}
