/*
Copyright 2025 Millstone HQ.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type SettingsInitParameters struct {

	// Link to your external ACL definition or management system. Must be a valid URL.
	AclsExternalLink *string `json:"aclsExternalLink,omitempty" tf:"acls_external_link,omitempty"`

	AclsExternallyManagedOn *bool `json:"aclsExternallyManagedOn,omitempty" tf:"acls_externally_managed_on,omitempty"`

	// Whether device approval is enabled for the tailnet
	DevicesApprovalOn *bool `json:"devicesApprovalOn,omitempty" tf:"devices_approval_on,omitempty"`

	// Whether auto updates are enabled for devices that belong to this tailnet
	DevicesAutoUpdatesOn *bool `json:"devicesAutoUpdatesOn,omitempty" tf:"devices_auto_updates_on,omitempty"`

	// The key expiry duration for devices on this tailnet
	DevicesKeyDurationDays *float64 `json:"devicesKeyDurationDays,omitempty" tf:"devices_key_duration_days,omitempty"`

	// Whether network flog logs are enabled for the tailnet
	NetworkFlowLoggingOn *bool `json:"networkFlowLoggingOn,omitempty" tf:"network_flow_logging_on,omitempty"`

	// Whether identity collection is enabled for device posture integrations for the tailnet
	PostureIdentityCollectionOn *bool `json:"postureIdentityCollectionOn,omitempty" tf:"posture_identity_collection_on,omitempty"`

	// Whether regional routing is enabled for the tailnet
	RegionalRoutingOn *bool `json:"regionalRoutingOn,omitempty" tf:"regional_routing_on,omitempty"`

	// Whether user approval is enabled for this tailnet
	UsersApprovalOn *bool `json:"usersApprovalOn,omitempty" tf:"users_approval_on,omitempty"`

	// Which user roles are allowed to join external tailnets
	UsersRoleAllowedToJoinExternalTailnet *string `json:"usersRoleAllowedToJoinExternalTailnet,omitempty" tf:"users_role_allowed_to_join_external_tailnet,omitempty"`
}

type SettingsObservation struct {

	// Link to your external ACL definition or management system. Must be a valid URL.
	AclsExternalLink *string `json:"aclsExternalLink,omitempty" tf:"acls_external_link,omitempty"`

	AclsExternallyManagedOn *bool `json:"aclsExternallyManagedOn,omitempty" tf:"acls_externally_managed_on,omitempty"`

	// Whether device approval is enabled for the tailnet
	DevicesApprovalOn *bool `json:"devicesApprovalOn,omitempty" tf:"devices_approval_on,omitempty"`

	// Whether auto updates are enabled for devices that belong to this tailnet
	DevicesAutoUpdatesOn *bool `json:"devicesAutoUpdatesOn,omitempty" tf:"devices_auto_updates_on,omitempty"`

	// The key expiry duration for devices on this tailnet
	DevicesKeyDurationDays *float64 `json:"devicesKeyDurationDays,omitempty" tf:"devices_key_duration_days,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether network flog logs are enabled for the tailnet
	NetworkFlowLoggingOn *bool `json:"networkFlowLoggingOn,omitempty" tf:"network_flow_logging_on,omitempty"`

	// Whether identity collection is enabled for device posture integrations for the tailnet
	PostureIdentityCollectionOn *bool `json:"postureIdentityCollectionOn,omitempty" tf:"posture_identity_collection_on,omitempty"`

	// Whether regional routing is enabled for the tailnet
	RegionalRoutingOn *bool `json:"regionalRoutingOn,omitempty" tf:"regional_routing_on,omitempty"`

	// Whether user approval is enabled for this tailnet
	UsersApprovalOn *bool `json:"usersApprovalOn,omitempty" tf:"users_approval_on,omitempty"`

	// Which user roles are allowed to join external tailnets
	UsersRoleAllowedToJoinExternalTailnet *string `json:"usersRoleAllowedToJoinExternalTailnet,omitempty" tf:"users_role_allowed_to_join_external_tailnet,omitempty"`
}

type SettingsParameters struct {

	// Link to your external ACL definition or management system. Must be a valid URL.
	// +kubebuilder:validation:Optional
	AclsExternalLink *string `json:"aclsExternalLink,omitempty" tf:"acls_external_link,omitempty"`

	// +kubebuilder:validation:Optional
	AclsExternallyManagedOn *bool `json:"aclsExternallyManagedOn,omitempty" tf:"acls_externally_managed_on,omitempty"`

	// Whether device approval is enabled for the tailnet
	// +kubebuilder:validation:Optional
	DevicesApprovalOn *bool `json:"devicesApprovalOn,omitempty" tf:"devices_approval_on,omitempty"`

	// Whether auto updates are enabled for devices that belong to this tailnet
	// +kubebuilder:validation:Optional
	DevicesAutoUpdatesOn *bool `json:"devicesAutoUpdatesOn,omitempty" tf:"devices_auto_updates_on,omitempty"`

	// The key expiry duration for devices on this tailnet
	// +kubebuilder:validation:Optional
	DevicesKeyDurationDays *float64 `json:"devicesKeyDurationDays,omitempty" tf:"devices_key_duration_days,omitempty"`

	// Whether network flog logs are enabled for the tailnet
	// +kubebuilder:validation:Optional
	NetworkFlowLoggingOn *bool `json:"networkFlowLoggingOn,omitempty" tf:"network_flow_logging_on,omitempty"`

	// Whether identity collection is enabled for device posture integrations for the tailnet
	// +kubebuilder:validation:Optional
	PostureIdentityCollectionOn *bool `json:"postureIdentityCollectionOn,omitempty" tf:"posture_identity_collection_on,omitempty"`

	// Whether regional routing is enabled for the tailnet
	// +kubebuilder:validation:Optional
	RegionalRoutingOn *bool `json:"regionalRoutingOn,omitempty" tf:"regional_routing_on,omitempty"`

	// Whether user approval is enabled for this tailnet
	// +kubebuilder:validation:Optional
	UsersApprovalOn *bool `json:"usersApprovalOn,omitempty" tf:"users_approval_on,omitempty"`

	// Which user roles are allowed to join external tailnets
	// +kubebuilder:validation:Optional
	UsersRoleAllowedToJoinExternalTailnet *string `json:"usersRoleAllowedToJoinExternalTailnet,omitempty" tf:"users_role_allowed_to_join_external_tailnet,omitempty"`
}

// SettingsSpec defines the desired state of Settings
type SettingsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     SettingsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SettingsInitParameters `json:"initProvider,omitempty"`
}

// SettingsStatus defines the observed state of Settings.
type SettingsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        SettingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Settings is the Schema for the Settingss API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,tailscale}
type Settings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              SettingsSpec   `json:"spec"`
	Status            SettingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SettingsList contains a list of Settingss
type SettingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Settings `json:"items"`
}

// Repository type metadata.
var (
	Settings_Kind             = "Settings"
	Settings_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Settings_Kind}.String()
	Settings_KindAPIVersion   = Settings_Kind + "." + CRDGroupVersion.String()
	Settings_GroupVersionKind = CRDGroupVersion.WithKind(Settings_Kind)
)

func init() {
	SchemeBuilder.Register(&Settings{}, &SettingsList{})
}
