/*
Copyright 2025 Millstone HQ.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type NameserversInitParameters struct {

	// Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.
	Nameservers []*string `json:"nameservers,omitempty" tf:"nameservers,omitempty"`
}

type NameserversObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.
	Nameservers []*string `json:"nameservers,omitempty" tf:"nameservers,omitempty"`
}

type NameserversParameters struct {

	// Devices on your network will use these nameservers to resolve DNS names. IPv4 or IPv6 addresses are accepted.
	// +kubebuilder:validation:Optional
	Nameservers []*string `json:"nameservers,omitempty" tf:"nameservers,omitempty"`
}

// NameserversSpec defines the desired state of Nameservers
type NameserversSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     NameserversParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NameserversInitParameters `json:"initProvider,omitempty"`
}

// NameserversStatus defines the observed state of Nameservers.
type NameserversStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        NameserversObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Nameservers is the Schema for the Nameserverss API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,tailscale}
type Nameservers struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nameservers) || (has(self.initProvider) && has(self.initProvider.nameservers))",message="spec.forProvider.nameservers is a required parameter"
	Spec   NameserversSpec   `json:"spec"`
	Status NameserversStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NameserversList contains a list of Nameserverss
type NameserversList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Nameservers `json:"items"`
}

// Repository type metadata.
var (
	Nameservers_Kind             = "Nameservers"
	Nameservers_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Nameservers_Kind}.String()
	Nameservers_KindAPIVersion   = Nameservers_Kind + "." + CRDGroupVersion.String()
	Nameservers_GroupVersionKind = CRDGroupVersion.WithKind(Nameservers_Kind)
)

func init() {
	SchemeBuilder.Register(&Nameservers{}, &NameserversList{})
}
